// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AddTaskController from "./add_task_controller"
application.register("add-task", AddTaskController)

import ChatroomSubscriptionController from "./chatroom_subscription_controller"
application.register("chatroom-subscription", ChatroomSubscriptionController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import TimerController from "./timer_controller"
application.register("timer", TimerController)

import RemovalsController from "./removals_controller"
application.register("removals", RemovalsController)